name: Publish GitHub release
on: [push]

jobs:
   

  rebuild:
    name: Rebuild the rootfs.tar.gz
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Create the rootfs
        run: ./build.py

      - name: Get the short version of the last commit
        id: vars
        run: |
          echo "tag_name=$(date +%Y.%m.%d.%H.%M)" >> $GITHUB_OUTPUT

      - name: Create the GH release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: ${{ steps.vars.outputs.tag_name }}

