name: Publish to PyPI
on: [push]

jobs:

  Release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Need to publish to PyPI
    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2

      - name: Install dependencies
        run: |
          pdm sync

      - name: Build before sending to release
        run: |
          pdm build

      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
